# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_configuration.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName(_fromUtf8("Configuration"))
        Configuration.resize(601, 453)
        self.verticalLayout = QtGui.QVBoxLayout(Configuration)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Configuration)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.optionsTab = QtGui.QWidget()
        self.optionsTab.setObjectName(_fromUtf8("optionsTab"))
        self.formLayout = QtGui.QFormLayout(self.optionsTab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.geomapfish_limitLabel = QtGui.QLabel(self.optionsTab)
        self.geomapfish_limitLabel.setObjectName(_fromUtf8("geomapfish_limitLabel"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.geomapfish_limitLabel)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.categoryLimit = QtGui.QSpinBox(self.optionsTab)
        self.categoryLimit.setMinimum(1)
        self.categoryLimit.setMaximum(1000)
        self.categoryLimit.setProperty("value", 10)
        self.categoryLimit.setObjectName(_fromUtf8("categoryLimit"))
        self.horizontalLayout_6.addWidget(self.categoryLimit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.geomapfish_partitionlimitLabel = QtGui.QLabel(self.optionsTab)
        self.geomapfish_partitionlimitLabel.setObjectName(_fromUtf8("geomapfish_partitionlimitLabel"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.geomapfish_partitionlimitLabel)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.totalLimit = QtGui.QSpinBox(self.optionsTab)
        self.totalLimit.setMinimum(1)
        self.totalLimit.setMaximum(1000)
        self.totalLimit.setProperty("value", 80)
        self.totalLimit.setObjectName(_fromUtf8("totalLimit"))
        self.horizontalLayout_5.addWidget(self.totalLimit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.formLayout.setLayout(2, QtGui.QFormLayout.SpanningRole, self.formLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.optionsTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.historyLength = QtGui.QSpinBox(self.optionsTab)
        self.historyLength.setMinimum(1)
        self.historyLength.setMaximum(10)
        self.historyLength.setProperty("value", 3)
        self.historyLength.setObjectName(_fromUtf8("historyLength"))
        self.horizontalLayout_2.addWidget(self.historyLength)
        self.label_3 = QtGui.QLabel(self.optionsTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.formLayout.setLayout(1, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.tabWidget.addTab(self.optionsTab, _fromUtf8(""))
        self.projectTab = QtGui.QWidget()
        self.projectTab.setObjectName(_fromUtf8("projectTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.projectTab)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.project = QtGui.QGroupBox(self.projectTab)
        self.project.setCheckable(True)
        self.project.setObjectName(_fromUtf8("project"))
        self.gridLayout = QtGui.QGridLayout(self.project)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_2 = QtGui.QLabel(self.project)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_9.addWidget(self.label_2)
        self.qftsfilepath = QtGui.QLineEdit(self.project)
        self.qftsfilepath.setReadOnly(True)
        self.qftsfilepath.setObjectName(_fromUtf8("qftsfilepath"))
        self.horizontalLayout_9.addWidget(self.qftsfilepath)
        self.openFileButton = QtGui.QToolButton(self.project)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/quickfinder/icons/open.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFileButton.setIcon(icon)
        self.openFileButton.setObjectName(_fromUtf8("openFileButton"))
        self.horizontalLayout_9.addWidget(self.openFileButton)
        self.createFileButton = QtGui.QToolButton(self.project)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/quickfinder/icons/new.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createFileButton.setIcon(icon1)
        self.createFileButton.setObjectName(_fromUtf8("createFileButton"))
        self.horizontalLayout_9.addWidget(self.createFileButton)
        self.gridLayout.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.projectSearchTable = QtGui.QTableView(self.project)
        self.projectSearchTable.setEnabled(False)
        self.projectSearchTable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.projectSearchTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.projectSearchTable.setSortingEnabled(True)
        self.projectSearchTable.setObjectName(_fromUtf8("projectSearchTable"))
        self.projectSearchTable.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.projectSearchTable, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.refreshAuto = QtGui.QCheckBox(self.project)
        self.refreshAuto.setChecked(True)
        self.refreshAuto.setObjectName(_fromUtf8("refreshAuto"))
        self.horizontalLayout_10.addWidget(self.refreshAuto)
        self.refreshDelay = QtGui.QSpinBox(self.project)
        self.refreshDelay.setMinimum(1)
        self.refreshDelay.setMaximum(999)
        self.refreshDelay.setProperty("value", 15)
        self.refreshDelay.setObjectName(_fromUtf8("refreshDelay"))
        self.horizontalLayout_10.addWidget(self.refreshDelay)
        self.label_4 = QtGui.QLabel(self.project)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_10.addWidget(self.label_4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.projectSearchButtonsWidget = QtGui.QWidget(self.project)
        self.projectSearchButtonsWidget.setObjectName(_fromUtf8("projectSearchButtonsWidget"))
        self.projectSearchButtonsLayout = QtGui.QHBoxLayout(self.projectSearchButtonsWidget)
        self.projectSearchButtonsLayout.setMargin(0)
        self.projectSearchButtonsLayout.setObjectName(_fromUtf8("projectSearchButtonsLayout"))
        self.addSearchButton = QtGui.QToolButton(self.projectSearchButtonsWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/quickfinder/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addSearchButton.setIcon(icon2)
        self.addSearchButton.setObjectName(_fromUtf8("addSearchButton"))
        self.projectSearchButtonsLayout.addWidget(self.addSearchButton)
        self.removeSearchButton = QtGui.QToolButton(self.projectSearchButtonsWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/quickfinder/icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeSearchButton.setIcon(icon3)
        self.removeSearchButton.setObjectName(_fromUtf8("removeSearchButton"))
        self.projectSearchButtonsLayout.addWidget(self.removeSearchButton)
        self.editSearchButton = QtGui.QToolButton(self.projectSearchButtonsWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/quickfinder/icons/edit.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editSearchButton.setIcon(icon4)
        self.editSearchButton.setObjectName(_fromUtf8("editSearchButton"))
        self.projectSearchButtonsLayout.addWidget(self.editSearchButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.projectSearchButtonsLayout.addItem(spacerItem4)
        self.refreshButton = QtGui.QToolButton(self.projectSearchButtonsWidget)
        self.refreshButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/quickfinder/icons/refresh.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon5)
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.projectSearchButtonsLayout.addWidget(self.refreshButton)
        self.gridLayout.addWidget(self.projectSearchButtonsWidget, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.project)
        self.tabWidget.addTab(self.projectTab, _fromUtf8(""))
        self.postgisTab = QtGui.QWidget()
        self.postgisTab.setObjectName(_fromUtf8("postgisTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.postgisTab)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.postgis = QtGui.QGroupBox(self.postgisTab)
        self.postgis.setEnabled(True)
        self.postgis.setCheckable(True)
        self.postgis.setObjectName(_fromUtf8("postgis"))
        self.gridLayout_2 = QtGui.QGridLayout(self.postgis)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.postgisSearchButtonsWidget = QtGui.QWidget(self.postgis)
        self.postgisSearchButtonsWidget.setObjectName(_fromUtf8("postgisSearchButtonsWidget"))
        self.projectSearchButtonsLayout_2 = QtGui.QHBoxLayout(self.postgisSearchButtonsWidget)
        self.projectSearchButtonsLayout_2.setMargin(0)
        self.projectSearchButtonsLayout_2.setObjectName(_fromUtf8("projectSearchButtonsLayout_2"))
        self.addPostgisSearchButton = QtGui.QToolButton(self.postgisSearchButtonsWidget)
        self.addPostgisSearchButton.setIcon(icon2)
        self.addPostgisSearchButton.setObjectName(_fromUtf8("addPostgisSearchButton"))
        self.projectSearchButtonsLayout_2.addWidget(self.addPostgisSearchButton)
        self.removePostgisSearchButton = QtGui.QToolButton(self.postgisSearchButtonsWidget)
        self.removePostgisSearchButton.setIcon(icon3)
        self.removePostgisSearchButton.setObjectName(_fromUtf8("removePostgisSearchButton"))
        self.projectSearchButtonsLayout_2.addWidget(self.removePostgisSearchButton)
        self.editPostgisSearchButton = QtGui.QToolButton(self.postgisSearchButtonsWidget)
        self.editPostgisSearchButton.setIcon(icon4)
        self.editPostgisSearchButton.setObjectName(_fromUtf8("editPostgisSearchButton"))
        self.projectSearchButtonsLayout_2.addWidget(self.editPostgisSearchButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.projectSearchButtonsLayout_2.addItem(spacerItem5)
        self.gridLayout_2.addWidget(self.postgisSearchButtonsWidget, 1, 0, 1, 2)
        self.postgisSearchTable = QtGui.QTableView(self.postgis)
        self.postgisSearchTable.setEnabled(True)
        self.postgisSearchTable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.postgisSearchTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.postgisSearchTable.setSortingEnabled(True)
        self.postgisSearchTable.setObjectName(_fromUtf8("postgisSearchTable"))
        self.postgisSearchTable.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.postgisSearchTable, 2, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.postgis)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.postgisConnection = QtGui.QComboBox(self.postgis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postgisConnection.sizePolicy().hasHeightForWidth())
        self.postgisConnection.setSizePolicy(sizePolicy)
        self.postgisConnection.setObjectName(_fromUtf8("postgisConnection"))
        self.gridLayout_2.addWidget(self.postgisConnection, 0, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.postgis)
        self.tabWidget.addTab(self.postgisTab, _fromUtf8(""))
        self.servicesTab = QtGui.QWidget()
        self.servicesTab.setObjectName(_fromUtf8("servicesTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.servicesTab)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.osm = QtGui.QGroupBox(self.servicesTab)
        self.osm.setCheckable(True)
        self.osm.setObjectName(_fromUtf8("osm"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.osm)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.osmUrlLabel = QtGui.QLabel(self.osm)
        self.osmUrlLabel.setObjectName(_fromUtf8("osmUrlLabel"))
        self.horizontalLayout_8.addWidget(self.osmUrlLabel)
        self.osmUrl = QtGui.QLineEdit(self.osm)
        self.osmUrl.setObjectName(_fromUtf8("osmUrl"))
        self.horizontalLayout_8.addWidget(self.osmUrl)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addWidget(self.osm)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.geomapfish = QtGui.QGroupBox(self.servicesTab)
        self.geomapfish.setCheckable(True)
        self.geomapfish.setObjectName(_fromUtf8("geomapfish"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.geomapfish)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.geomapfish_urlLabel = QtGui.QLabel(self.geomapfish)
        self.geomapfish_urlLabel.setObjectName(_fromUtf8("geomapfish_urlLabel"))
        self.horizontalLayout_4.addWidget(self.geomapfish_urlLabel)
        self.geomapfishUrl = QtGui.QLineEdit(self.geomapfish)
        self.geomapfishUrl.setObjectName(_fromUtf8("geomapfishUrl"))
        self.horizontalLayout_4.addWidget(self.geomapfishUrl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.geomapfishCrsLabel = QtGui.QLabel(self.geomapfish)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geomapfishCrsLabel.sizePolicy().hasHeightForWidth())
        self.geomapfishCrsLabel.setSizePolicy(sizePolicy)
        self.geomapfishCrsLabel.setObjectName(_fromUtf8("geomapfishCrsLabel"))
        self.horizontalLayout_3.addWidget(self.geomapfishCrsLabel)
        self.geomapfishCrs = QtGui.QLineEdit(self.geomapfish)
        self.geomapfishCrs.setEnabled(True)
        self.geomapfishCrs.setInputMask(_fromUtf8(""))
        self.geomapfishCrs.setReadOnly(True)
        self.geomapfishCrs.setObjectName(_fromUtf8("geomapfishCrs"))
        self.horizontalLayout_3.addWidget(self.geomapfishCrs)
        self.geomapfishCrsButton = QtGui.QPushButton(self.geomapfish)
        self.geomapfishCrsButton.setObjectName(_fromUtf8("geomapfishCrsButton"))
        self.horizontalLayout_3.addWidget(self.geomapfishCrsButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.geomapfishUserLabel = QtGui.QLabel(self.geomapfish)
        self.geomapfishUserLabel.setObjectName(_fromUtf8("geomapfishUserLabel"))
        self.horizontalLayout.addWidget(self.geomapfishUserLabel)
        self.geomapfishUser = QtGui.QLineEdit(self.geomapfish)
        self.geomapfishUser.setObjectName(_fromUtf8("geomapfishUser"))
        self.horizontalLayout.addWidget(self.geomapfishUser)
        self.geomapfishPassLabel = QtGui.QLabel(self.geomapfish)
        self.geomapfishPassLabel.setObjectName(_fromUtf8("geomapfishPassLabel"))
        self.horizontalLayout.addWidget(self.geomapfishPassLabel)
        self.geomapfishPass = QtGui.QLineEdit(self.geomapfish)
        self.geomapfishPass.setEchoMode(QtGui.QLineEdit.Password)
        self.geomapfishPass.setObjectName(_fromUtf8("geomapfishPass"))
        self.horizontalLayout.addWidget(self.geomapfishPass)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.geomapfish)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.tabWidget.addTab(self.servicesTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Configuration)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Configuration)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Configuration.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Configuration.reject)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        Configuration.setWindowTitle(_translate("Configuration", "Quick Finder - Configuration", None))
        self.geomapfish_limitLabel.setText(_translate("Configuration", "Limit per layer/category", None))
        self.geomapfish_partitionlimitLabel.setText(_translate("Configuration", "Total limit per service", None))
        self.label.setText(_translate("Configuration", "Keep last", None))
        self.label_3.setText(_translate("Configuration", "text searches", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionsTab), _translate("Configuration", "General", None))
        self.project.setTitle(_translate("Configuration", "Search in project layers", None))
        self.label_2.setText(_translate("Configuration", "QuickFinder file", None))
        self.openFileButton.setToolTip(_translate("Configuration", "Open existing QuickFinder file", None))
        self.openFileButton.setText(_translate("Configuration", "...", None))
        self.createFileButton.setToolTip(_translate("Configuration", "Create a new QuickFinder file", None))
        self.createFileButton.setText(_translate("Configuration", "Create a new QuickFinder file", None))
        self.refreshAuto.setText(_translate("Configuration", "Automatically refresh after", None))
        self.label_4.setText(_translate("Configuration", "day(s)", None))
        self.addSearchButton.setToolTip(_translate("Configuration", "Add a new layer search", None))
        self.removeSearchButton.setToolTip(_translate("Configuration", "Remove", None))
        self.removeSearchButton.setText(_translate("Configuration", "...", None))
        self.editSearchButton.setToolTip(_translate("Configuration", "Edit", None))
        self.editSearchButton.setText(_translate("Configuration", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("Configuration", "Project search", None))
        self.postgis.setTitle(_translate("Configuration", "Search in PostGIS database", None))
        self.addPostgisSearchButton.setToolTip(_translate("Configuration", "Add a new layer search", None))
        self.removePostgisSearchButton.setToolTip(_translate("Configuration", "Remove", None))
        self.removePostgisSearchButton.setText(_translate("Configuration", "...", None))
        self.editPostgisSearchButton.setToolTip(_translate("Configuration", "Edit", None))
        self.editPostgisSearchButton.setText(_translate("Configuration", "...", None))
        self.label_5.setText(_translate("Configuration", "Connection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.postgisTab), _translate("Configuration", "PostGIS", None))
        self.osm.setTitle(_translate("Configuration", "OpenStreetMap", None))
        self.osmUrlLabel.setText(_translate("Configuration", "Url", None))
        self.geomapfish.setTitle(_translate("Configuration", "GeoMapFish", None))
        self.geomapfish_urlLabel.setText(_translate("Configuration", "Url", None))
        self.geomapfishCrsLabel.setText(_translate("Configuration", "Coordinate Reference System", None))
        self.geomapfishCrsButton.setText(_translate("Configuration", "Select", None))
        self.geomapfishUserLabel.setText(_translate("Configuration", "User", None))
        self.geomapfishPassLabel.setText(_translate("Configuration", "Password", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.servicesTab), _translate("Configuration", "Remote services", None))

from . import resources_rc
