# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\len\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfinder\ui\ui_configuration.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName("Configuration")
        Configuration.resize(680, 445)
        self.verticalLayout = QtWidgets.QVBoxLayout(Configuration)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Configuration)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.optionsTab = QtWidgets.QWidget()
        self.optionsTab.setObjectName("optionsTab")
        self.formLayout = QtWidgets.QFormLayout(self.optionsTab)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.geomapfish_limitLabel = QtWidgets.QLabel(self.optionsTab)
        self.geomapfish_limitLabel.setObjectName("geomapfish_limitLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.geomapfish_limitLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.categoryLimit = QtWidgets.QSpinBox(self.optionsTab)
        self.categoryLimit.setMinimum(1)
        self.categoryLimit.setMaximum(1000)
        self.categoryLimit.setProperty("value", 10)
        self.categoryLimit.setObjectName("categoryLimit")
        self.horizontalLayout_6.addWidget(self.categoryLimit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.geomapfish_partitionlimitLabel = QtWidgets.QLabel(self.optionsTab)
        self.geomapfish_partitionlimitLabel.setObjectName("geomapfish_partitionlimitLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.geomapfish_partitionlimitLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.totalLimit = QtWidgets.QSpinBox(self.optionsTab)
        self.totalLimit.setMinimum(1)
        self.totalLimit.setMaximum(1000)
        self.totalLimit.setProperty("value", 80)
        self.totalLimit.setObjectName("totalLimit")
        self.horizontalLayout_5.addWidget(self.totalLimit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.formLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.optionsTab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.historyLength = QtWidgets.QSpinBox(self.optionsTab)
        self.historyLength.setMinimum(1)
        self.historyLength.setMaximum(10)
        self.historyLength.setProperty("value", 3)
        self.historyLength.setObjectName("historyLength")
        self.horizontalLayout_2.addWidget(self.historyLength)
        self.label_3 = QtWidgets.QLabel(self.optionsTab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.tabWidget.addTab(self.optionsTab, "")
        self.projectTab = QtWidgets.QWidget()
        self.projectTab.setObjectName("projectTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.projectTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.project = QtWidgets.QGroupBox(self.projectTab)
        self.project.setCheckable(True)
        self.project.setObjectName("project")
        self.gridLayout = QtWidgets.QGridLayout(self.project)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.project)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.qftsfilepath = QtWidgets.QLineEdit(self.project)
        self.qftsfilepath.setReadOnly(True)
        self.qftsfilepath.setObjectName("qftsfilepath")
        self.horizontalLayout_9.addWidget(self.qftsfilepath)
        self.openFileButton = QtWidgets.QToolButton(self.project)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/quickfinder/icons/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFileButton.setIcon(icon)
        self.openFileButton.setObjectName("openFileButton")
        self.horizontalLayout_9.addWidget(self.openFileButton)
        self.createFileButton = QtWidgets.QToolButton(self.project)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/quickfinder/icons/new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createFileButton.setIcon(icon1)
        self.createFileButton.setObjectName("createFileButton")
        self.horizontalLayout_9.addWidget(self.createFileButton)
        self.gridLayout.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.projectSearchTable = QtWidgets.QTableView(self.project)
        self.projectSearchTable.setEnabled(False)
        self.projectSearchTable.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.projectSearchTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.projectSearchTable.setSortingEnabled(True)
        self.projectSearchTable.setObjectName("projectSearchTable")
        self.projectSearchTable.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.projectSearchTable, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.refreshAuto = QtWidgets.QCheckBox(self.project)
        self.refreshAuto.setChecked(True)
        self.refreshAuto.setObjectName("refreshAuto")
        self.horizontalLayout_10.addWidget(self.refreshAuto)
        self.refreshDelay = QtWidgets.QSpinBox(self.project)
        self.refreshDelay.setMinimum(1)
        self.refreshDelay.setMaximum(999)
        self.refreshDelay.setProperty("value", 15)
        self.refreshDelay.setObjectName("refreshDelay")
        self.horizontalLayout_10.addWidget(self.refreshDelay)
        self.label_4 = QtWidgets.QLabel(self.project)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.projectSearchButtonsWidget = QtWidgets.QWidget(self.project)
        self.projectSearchButtonsWidget.setObjectName("projectSearchButtonsWidget")
        self.projectSearchButtonsLayout = QtWidgets.QHBoxLayout(self.projectSearchButtonsWidget)
        self.projectSearchButtonsLayout.setContentsMargins(0, 0, 0, 0)
        self.projectSearchButtonsLayout.setObjectName("projectSearchButtonsLayout")
        self.addSearchButton = QtWidgets.QToolButton(self.projectSearchButtonsWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/quickfinder/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addSearchButton.setIcon(icon2)
        self.addSearchButton.setObjectName("addSearchButton")
        self.projectSearchButtonsLayout.addWidget(self.addSearchButton)
        self.removeSearchButton = QtWidgets.QToolButton(self.projectSearchButtonsWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/quickfinder/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeSearchButton.setIcon(icon3)
        self.removeSearchButton.setObjectName("removeSearchButton")
        self.projectSearchButtonsLayout.addWidget(self.removeSearchButton)
        self.editSearchButton = QtWidgets.QToolButton(self.projectSearchButtonsWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/quickfinder/icons/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editSearchButton.setIcon(icon4)
        self.editSearchButton.setObjectName("editSearchButton")
        self.projectSearchButtonsLayout.addWidget(self.editSearchButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.projectSearchButtonsLayout.addItem(spacerItem4)
        self.refreshButton = QtWidgets.QToolButton(self.projectSearchButtonsWidget)
        self.refreshButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/quickfinder/icons/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon5)
        self.refreshButton.setObjectName("refreshButton")
        self.projectSearchButtonsLayout.addWidget(self.refreshButton)
        self.gridLayout.addWidget(self.projectSearchButtonsWidget, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.project)
        self.tabWidget.addTab(self.projectTab, "")
        self.postgisTab = QtWidgets.QWidget()
        self.postgisTab.setObjectName("postgisTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.postgisTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.postgis = QtWidgets.QGroupBox(self.postgisTab)
        self.postgis.setEnabled(True)
        self.postgis.setCheckable(True)
        self.postgis.setObjectName("postgis")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.postgis)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.postgisSearchButtonsWidget = QtWidgets.QWidget(self.postgis)
        self.postgisSearchButtonsWidget.setObjectName("postgisSearchButtonsWidget")
        self.projectSearchButtonsLayout_2 = QtWidgets.QHBoxLayout(self.postgisSearchButtonsWidget)
        self.projectSearchButtonsLayout_2.setContentsMargins(0, 0, 0, 0)
        self.projectSearchButtonsLayout_2.setObjectName("projectSearchButtonsLayout_2")
        self.addPostgisSearchButton = QtWidgets.QToolButton(self.postgisSearchButtonsWidget)
        self.addPostgisSearchButton.setIcon(icon2)
        self.addPostgisSearchButton.setObjectName("addPostgisSearchButton")
        self.projectSearchButtonsLayout_2.addWidget(self.addPostgisSearchButton)
        self.removePostgisSearchButton = QtWidgets.QToolButton(self.postgisSearchButtonsWidget)
        self.removePostgisSearchButton.setIcon(icon3)
        self.removePostgisSearchButton.setObjectName("removePostgisSearchButton")
        self.projectSearchButtonsLayout_2.addWidget(self.removePostgisSearchButton)
        self.editPostgisSearchButton = QtWidgets.QToolButton(self.postgisSearchButtonsWidget)
        self.editPostgisSearchButton.setIcon(icon4)
        self.editPostgisSearchButton.setObjectName("editPostgisSearchButton")
        self.projectSearchButtonsLayout_2.addWidget(self.editPostgisSearchButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.projectSearchButtonsLayout_2.addItem(spacerItem5)
        self.gridLayout_2.addWidget(self.postgisSearchButtonsWidget, 1, 0, 1, 2)
        self.postgisSearchTable = QtWidgets.QTableView(self.postgis)
        self.postgisSearchTable.setEnabled(True)
        self.postgisSearchTable.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.postgisSearchTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.postgisSearchTable.setSortingEnabled(True)
        self.postgisSearchTable.setObjectName("postgisSearchTable")
        self.postgisSearchTable.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.postgisSearchTable, 2, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.postgis)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.postgisConnection = QtWidgets.QComboBox(self.postgis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postgisConnection.sizePolicy().hasHeightForWidth())
        self.postgisConnection.setSizePolicy(sizePolicy)
        self.postgisConnection.setObjectName("postgisConnection")
        self.gridLayout_2.addWidget(self.postgisConnection, 0, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.postgis)
        self.tabWidget.addTab(self.postgisTab, "")
        self.servicesTab = QtWidgets.QWidget()
        self.servicesTab.setObjectName("servicesTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.servicesTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.osm = QtWidgets.QGroupBox(self.servicesTab)
        self.osm.setCheckable(True)
        self.osm.setObjectName("osm")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.osm)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.osmUrlLabel = QtWidgets.QLabel(self.osm)
        self.osmUrlLabel.setObjectName("osmUrlLabel")
        self.horizontalLayout_8.addWidget(self.osmUrlLabel)
        self.osmUrl = QtWidgets.QLineEdit(self.osm)
        self.osmUrl.setObjectName("osmUrl")
        self.horizontalLayout_8.addWidget(self.osmUrl)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addWidget(self.osm)
        self.amap = QtWidgets.QGroupBox(self.servicesTab)
        self.amap.setCheckable(True)
        self.amap.setObjectName("amap")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.amap)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 611, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.amapUrl = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.amapUrl.setObjectName("amapUrl")
        self.horizontalLayout_7.addWidget(self.amapUrl)
        self.verticalLayout_2.addWidget(self.amap)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.tabWidget.addTab(self.servicesTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Configuration)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Configuration)
        self.tabWidget.setCurrentIndex(3)
        self.buttonBox.accepted.connect(Configuration.accept)
        self.buttonBox.rejected.connect(Configuration.reject)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        _translate = QtCore.QCoreApplication.translate
        Configuration.setWindowTitle(_translate("Configuration", "Quick Finder - Configuration"))
        self.geomapfish_limitLabel.setText(_translate("Configuration", "Limit per layer/category"))
        self.geomapfish_partitionlimitLabel.setText(_translate("Configuration", "Total limit per service"))
        self.label.setText(_translate("Configuration", "Keep last"))
        self.label_3.setText(_translate("Configuration", "text searches"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionsTab), _translate("Configuration", "General"))
        self.project.setTitle(_translate("Configuration", "Search in project layers"))
        self.label_2.setText(_translate("Configuration", "QuickFinder file"))
        self.openFileButton.setToolTip(_translate("Configuration", "Open existing QuickFinder file"))
        self.openFileButton.setText(_translate("Configuration", "..."))
        self.createFileButton.setToolTip(_translate("Configuration", "Create a new QuickFinder file"))
        self.createFileButton.setText(_translate("Configuration", "Create a new QuickFinder file"))
        self.refreshAuto.setText(_translate("Configuration", "Automatically refresh after"))
        self.label_4.setText(_translate("Configuration", "day(s)"))
        self.addSearchButton.setToolTip(_translate("Configuration", "Add a new layer search"))
        self.removeSearchButton.setToolTip(_translate("Configuration", "Remove"))
        self.removeSearchButton.setText(_translate("Configuration", "..."))
        self.editSearchButton.setToolTip(_translate("Configuration", "Edit"))
        self.editSearchButton.setText(_translate("Configuration", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("Configuration", "Project search"))
        self.postgis.setTitle(_translate("Configuration", "Search in PostGIS database"))
        self.addPostgisSearchButton.setToolTip(_translate("Configuration", "Add a new layer search"))
        self.removePostgisSearchButton.setToolTip(_translate("Configuration", "Remove"))
        self.removePostgisSearchButton.setText(_translate("Configuration", "..."))
        self.editPostgisSearchButton.setToolTip(_translate("Configuration", "Edit"))
        self.editPostgisSearchButton.setText(_translate("Configuration", "..."))
        self.label_5.setText(_translate("Configuration", "Connection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.postgisTab), _translate("Configuration", "PostGIS"))
        self.osm.setTitle(_translate("Configuration", "OpenStreetMap"))
        self.osmUrlLabel.setText(_translate("Configuration", "Url"))
        self.amap.setTitle(_translate("Configuration", "Amap"))
        self.label_6.setText(_translate("Configuration", "Url"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.servicesTab), _translate("Configuration", "Remote services"))
