# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_configuration.ui'
#
# Created: Wed Apr  2 09:39:13 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName(_fromUtf8("Settings"))
        Settings.resize(513, 427)
        self.verticalLayout = QtGui.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Settings)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.optionsTab = QtGui.QWidget()
        self.optionsTab.setObjectName(_fromUtf8("optionsTab"))
        self.formLayout = QtGui.QFormLayout(self.optionsTab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.optionsTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.historyLength = QtGui.QSpinBox(self.optionsTab)
        self.historyLength.setMinimum(1)
        self.historyLength.setMaximum(10)
        self.historyLength.setProperty("value", 3)
        self.historyLength.setObjectName(_fromUtf8("historyLength"))
        self.horizontalLayout_2.addWidget(self.historyLength)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.tabWidget.addTab(self.optionsTab, _fromUtf8(""))
        self.projectTab = QtGui.QWidget()
        self.projectTab.setObjectName(_fromUtf8("projectTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.projectTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.project = QtGui.QGroupBox(self.projectTab)
        self.project.setCheckable(True)
        self.project.setObjectName(_fromUtf8("project"))
        self.formLayout_2 = QtGui.QFormLayout(self.project)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.layerLabel = QtGui.QLabel(self.project)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerLabel.sizePolicy().hasHeightForWidth())
        self.layerLabel.setSizePolicy(sizePolicy)
        self.layerLabel.setObjectName(_fromUtf8("layerLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.layerLabel)
        self.layerId = QtGui.QComboBox(self.project)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerId.sizePolicy().hasHeightForWidth())
        self.layerId.setSizePolicy(sizePolicy)
        self.layerId.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.layerId.setObjectName(_fromUtf8("layerId"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.layerId)
        self.FieldNameLabel = QtGui.QLabel(self.project)
        self.FieldNameLabel.setObjectName(_fromUtf8("FieldNameLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.FieldNameLabel)
        self.fieldNameLayout = QtGui.QHBoxLayout()
        self.fieldNameLayout.setObjectName(_fromUtf8("fieldNameLayout"))
        self.fieldName = QtGui.QComboBox(self.project)
        self.fieldName.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldName.sizePolicy().hasHeightForWidth())
        self.fieldName.setSizePolicy(sizePolicy)
        self.fieldName.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.fieldName.setObjectName(_fromUtf8("fieldName"))
        self.fieldNameLayout.addWidget(self.fieldName)
        self.expressionButton = QtGui.QToolButton(self.project)
        self.expressionButton.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/quickfinder/icons/expression.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.expressionButton.setIcon(icon)
        self.expressionButton.setObjectName(_fromUtf8("expressionButton"))
        self.fieldNameLayout.addWidget(self.expressionButton)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.fieldNameLayout)
        self.project_layerlimitLabel = QtGui.QLabel(self.project)
        self.project_layerlimitLabel.setObjectName(_fromUtf8("project_layerlimitLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.project_layerlimitLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.project_layerlimit = QtGui.QSpinBox(self.project)
        self.project_layerlimit.setMinimum(1)
        self.project_layerlimit.setMaximum(1000)
        self.project_layerlimit.setProperty("value", 10)
        self.project_layerlimit.setObjectName(_fromUtf8("project_layerlimit"))
        self.horizontalLayout.addWidget(self.project_layerlimit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.project)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tabWidget.addTab(self.projectTab, _fromUtf8(""))
        self.servicesTab = QtGui.QWidget()
        self.servicesTab.setObjectName(_fromUtf8("servicesTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.servicesTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.osm = QtGui.QGroupBox(self.servicesTab)
        self.osm.setCheckable(True)
        self.osm.setObjectName(_fromUtf8("osm"))
        self.formLayout_3 = QtGui.QFormLayout(self.osm)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.osmLimitLabel = QtGui.QLabel(self.osm)
        self.osmLimitLabel.setObjectName(_fromUtf8("osmLimitLabel"))
        self.horizontalLayout_7.addWidget(self.osmLimitLabel)
        self.osmLimit = QtGui.QSpinBox(self.osm)
        self.osmLimit.setMinimum(1)
        self.osmLimit.setMaximum(1000)
        self.osmLimit.setProperty("value", 10)
        self.osmLimit.setObjectName(_fromUtf8("osmLimit"))
        self.horizontalLayout_7.addWidget(self.osmLimit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.formLayout_3.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.osmUrlLabel = QtGui.QLabel(self.osm)
        self.osmUrlLabel.setObjectName(_fromUtf8("osmUrlLabel"))
        self.horizontalLayout_8.addWidget(self.osmUrlLabel)
        self.osmUrl = QtGui.QLineEdit(self.osm)
        self.osmUrl.setObjectName(_fromUtf8("osmUrl"))
        self.horizontalLayout_8.addWidget(self.osmUrl)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.verticalLayout_2.addWidget(self.osm)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.geomapfish = QtGui.QGroupBox(self.servicesTab)
        self.geomapfish.setCheckable(True)
        self.geomapfish.setObjectName(_fromUtf8("geomapfish"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.geomapfish)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.geomapfishUrlLabel = QtGui.QLabel(self.geomapfish)
        self.geomapfishUrlLabel.setObjectName(_fromUtf8("geomapfishUrlLabel"))
        self.horizontalLayout_4.addWidget(self.geomapfishUrlLabel)
        self.geomapfishUrl = QtGui.QLineEdit(self.geomapfish)
        self.geomapfishUrl.setObjectName(_fromUtf8("geomapfishUrl"))
        self.horizontalLayout_4.addWidget(self.geomapfishUrl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.geomapfishCrsLabel = QtGui.QLabel(self.geomapfish)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geomapfishCrsLabel.sizePolicy().hasHeightForWidth())
        self.geomapfishCrsLabel.setSizePolicy(sizePolicy)
        self.geomapfishCrsLabel.setObjectName(_fromUtf8("geomapfishCrsLabel"))
        self.horizontalLayout_3.addWidget(self.geomapfishCrsLabel)
        self.geomapfishCrs = QtGui.QLineEdit(self.geomapfish)
        self.geomapfishCrs.setEnabled(True)
        self.geomapfishCrs.setInputMask(_fromUtf8(""))
        self.geomapfishCrs.setReadOnly(True)
        self.geomapfishCrs.setObjectName(_fromUtf8("geomapfishCrs"))
        self.horizontalLayout_3.addWidget(self.geomapfishCrs)
        self.geomapfishCrsButton = QtGui.QPushButton(self.geomapfish)
        self.geomapfishCrsButton.setObjectName(_fromUtf8("geomapfishCrsButton"))
        self.horizontalLayout_3.addWidget(self.geomapfishCrsButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.geomapfish_limitLabel = QtGui.QLabel(self.geomapfish)
        self.geomapfish_limitLabel.setObjectName(_fromUtf8("geomapfish_limitLabel"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.geomapfish_limitLabel)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.geomapfish_limit_2 = QtGui.QSpinBox(self.geomapfish)
        self.geomapfish_limit_2.setMinimum(1)
        self.geomapfish_limit_2.setMaximum(1000)
        self.geomapfish_limit_2.setProperty("value", 20)
        self.geomapfish_limit_2.setObjectName(_fromUtf8("geomapfish_limit_2"))
        self.horizontalLayout_6.addWidget(self.geomapfish_limit_2)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.geomapfish_partitionlimitLabel = QtGui.QLabel(self.geomapfish)
        self.geomapfish_partitionlimitLabel.setObjectName(_fromUtf8("geomapfish_partitionlimitLabel"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.geomapfish_partitionlimitLabel)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.geomapfish_partitionlimit = QtGui.QSpinBox(self.geomapfish)
        self.geomapfish_partitionlimit.setMinimum(1)
        self.geomapfish_partitionlimit.setMaximum(1000)
        self.geomapfish_partitionlimit.setProperty("value", 10)
        self.geomapfish_partitionlimit.setObjectName(_fromUtf8("geomapfish_partitionlimit"))
        self.horizontalLayout_5.addWidget(self.geomapfish_partitionlimit)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.formLayout_4.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.verticalLayout_2.addWidget(self.geomapfish)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.tabWidget.addTab(self.servicesTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Settings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(_translate("Settings", "Quick Finder - Settings", None))
        self.label.setText(_translate("Settings", "Search history length", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionsTab), _translate("Settings", "General", None))
        self.project.setTitle(_translate("Settings", "Project", None))
        self.layerLabel.setText(_translate("Settings", "Layer", None))
        self.FieldNameLabel.setText(_translate("Settings", "Field", None))
        self.expressionButton.setText(_translate("Settings", "...", None))
        self.project_layerlimitLabel.setText(_translate("Settings", "Per layer limit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("Settings", "Project layers", None))
        self.osm.setTitle(_translate("Settings", "OpenStreetMap", None))
        self.osmLimitLabel.setText(_translate("Settings", "Total limit", None))
        self.osmUrlLabel.setText(_translate("Settings", "Url", None))
        self.geomapfish.setTitle(_translate("Settings", "GeoMapFish", None))
        self.geomapfishUrlLabel.setText(_translate("Settings", "Url", None))
        self.geomapfishCrsLabel.setText(_translate("Settings", "Coordinate Reference System", None))
        self.geomapfishCrsButton.setText(_translate("Settings", "Select", None))
        self.geomapfish_limitLabel.setText(_translate("Settings", "Total limit", None))
        self.geomapfish_partitionlimitLabel.setText(_translate("Settings", "Per layer limit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.servicesTab), _translate("Settings", "Services", None))

import resources_rc
